language: node_js
deploy:
  provider: npm
  email: emil.kashkevich@gmail.com
  api_key:
    secure: v4t6ScqoUXbff40tx1zF+VRD2nwNsU8z0K/yINa4Fb9yRocGMkX3hyF85c4CLLVy07UxLf4DBKF5llE8z3iBgScoAcvT4VwDxvP1LZx1VdlGh/+88H+lOWTVtPfovkH7P2NkMoXkJDHHKeQo1eLo2LSGKMeyZ31/Vy+BEJRjO6KeSsTp2vHxk52PR0BgPRJGJbiMmoTCRd4ecZjNk1KE/S+GNTqavM6wlAOhX4IeEs5pZPL+gFbjWQu2nwY49XyJbyvPnLAaBS0pDuxgDrHapHFcpc/XlLrFPrOvX6SHEfib7bKL1wCQxLUKkHucL5OPIgmVDyY8jIp639m7rONjvr+BDz4SMLWu0oQB+04AordpK/T9EQZZ0IGeGv4Sa/FsV1vjUYsvwY3TU0xYQ/W3XsYBqTI3AgN2ZBf0OxKonSWQhZOe7bXcagQ9RWSVXDq5U01wkT+XfRuHxkHhfMxzmZEwltf469V3g8Z/cyO6sr683TfKLdR8uFeaBbdje9x3qu08MvU3DC3ExghxFFjMzIDVHh+RToaw+4hLsnNKKwkNVy7BOV6LfJbWSao51pWlsvNaQBMtWVwZcwdfCwYHSNqn+EHsjNVC1W3N66sUmMn5o2tuZie2zNSVZfiiEPM/CBzphBPH+ePzdyiPMiCpaosUQ6MTwdBp+81PwNbTYg0=
  on:
    tags: true
    repo: lysyi3m/cantuse-db
    all_branches: true
  skip_cleanup: true
